tap 'jandedobbeleer/oh-my-posh'
tap 'pakerwreah/calendr'

brew 'git-delta'
brew 'nvm'
brew 'fzf'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'
brew 'jandedobbeleer/oh-my-posh/oh-my-posh'
brew 'zoxide'
brew 'tig'
brew 'eza'

cask 'visual-studio-code'
cask 'webstorm'
cask 'calendr'
# cask 'arc'
cask 'zen-browser'
cask 'wezterm'
cask 'appcleaner'
cask '1password'
cask '1password-cli'
cask 'gather'
cask 'orbstack'
cask 'slack'
cask 'spotify'
cask 'ollama'
cask 'raycast'
cask 'notunes'
# cask 'logitech-g-hub'
cask 'bruno'
cask 'hiddenbar'
cask 'notion'
cask 'linear-linear'
# cask 'stats'
cask 'lihaoyun6/tap/quickrecorder'
cask 'font-meslo-lg-nerd-font'