name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Install Homebrew
      shell: bash
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install Stow
      shell: bash
      run: brew install stow
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Execute full install
      run:  ./install.sh