name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install Stow    
      shell: bash
      run: brew install stow
    - name: Make install.sh executable
      run: chmod +x ./install.sh
    - name: Execute full install
      run:  ./install.sh
    - name: Cat ".zshrc"
      shell: bash  
      run: cat ~/.zshrc
    - name: 'Cat .gitconfig'
      shell: bash
      run: cat ~/.gitconfig